tickers:
  - QQQI
  - SCHD
  - TSM
  - ASML
  - LRCX
  - GOOGL
  - AAPL
  - IREN
  - NVDA
  - AMD
  - TTWO

names:            # optional: company names make news search more accurate
  QQQI: QQQI
  SCHD: SCHD
  TSM: TSMC
  ASML: ASML
  LRCX: Lam Research
  GOOGL: GOOGLE
  AAPL: APPLE
  IREN: Iris Energy
  NVDA: Nvidia
  AMD: AMD
  TTWO: Rockstar
max_news_per_ticker: 5
language: Thai   # Thai or English
